name: Build & Publish Docker Image

env:
  DOCKERHUB_TAG: "schwitzd/routeros-letsencrypt"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & capture version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Semantic-Release
        run: npm install -g semantic-release @semantic-release/release-notes-generator @semantic-release/git @semantic-release/github semantic-release-gha-output commit-analyzer-fail-on-no-release

      - name: Run Semantic-Release and capture version
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --ci

      - name: Save version to file
        run: echo "${{ steps.semantic-release.outputs.version }}" > assets/version.txt

      - name: Commit version.txt
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(release): update version to ${{ steps.semantic-release.outputs.version }}"
          file_pattern: assets/version.txt

  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.build.outputs.commit_hash }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: VERSION=${{ needs.build.outputs.version }}
          tags: |
            ${{ env.DOCKERHUB_TAG }}:latest
            ${{ env.DOCKERHUB_TAG }}:${{ needs.build.outputs.version }}
          platforms: linux/amd64,linux/arm64

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_TAG }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
          enable-url-completion: true
