name: Release Docker Image

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Semantic-Release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run Semantic-Release
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(npx semantic-release --dry-run | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo ${VERSION} > assets/version.txt
          git add assets/version.txt
          git commit -m "chore(release): update version to ${VERSION}"
          git push origin main
